---
version: "3.0"
services:
  node1:
    build: .
    container_name: node1
    environment:
      - TZ=America/New_York
    ports:
      - 22:22
    volumes:
      - /home/r2r0m0c0/:/data
    hostname: Node1
    restart: unless-stopped
